# frozen_string_literal: true
source 'http://rubygems.org'

group do
  gem 'activesupport'
  gem 'cucumber'
  gem 'capybara'
  gem 'selenium-webdriver'
  gem 'page-object'
  gem 'pry', '~> 0.9.12'
  gem 'json'
  gem 'jsonpath', '~> 0.5.8'
  gem 'rubocop'
  gem 'rest-client'
  gem 'colorize'
  gem 'mountebank'
  gem 'factory_girl'
  gem 'rspec'
  gem 'rspec-expectations'
  gem 'faker'
  gem 'syntax'
  gem 'capybara-screenshot'
  gem 'poltergeist'
  gem 'rake'
  gem 'database_cleaner'
end
